# Generated by Django 4.2.5 on 2023-09-16 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Renda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fonte_renda', models.CharField(max_length=255)),
                ('categoria_renda', models.CharField(default='ATIVA', max_length=255)),
                ('data', models.DateField(default='2023-09-10')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
