# Generated by Django 4.2.5 on 2023-09-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='data',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AddField(
            model_name='finance',
            name='valorativos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='finance',
            name='valordespesas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='finance',
            name='valorpassivos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='finance',
            name='valorrenda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='finance',
            name='ativos',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='finance',
            name='despesas',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='finance',
            name='passivos',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='finance',
            name='renda',
            field=models.CharField(max_length=255),
        ),
    ]
