# Generated by Django 4.2.5 on 2023-09-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_finance_data_finance_valorativos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finance',
        ),
    ]
